[tool.pylint.main]
py-version = "3.12"
extension-pkg-whitelist = ["PyQt6"]

[tool.pylint.basic]
# camelCase is more readable to me
argument-naming-style = "camelCase"
attr-naming-style = "camelCase"
function-naming-style = "camelCase"
method-naming-style = "camelCase"
module-naming-style = "camelCase"
variable-naming-style = "camelCase"
class-naming-style = "PascalCase"

docstring-min-length = 6 # on shorter functions, case by case basis

# allow generated members with pyjson5, otherwise pylint complains
generated-members = ["pyjson5.*", "pynmeagps.*"]

[tool.pylint.design]
max-args = 8        # default of 5 seems too low
max-attributes = 14 # default of 7 seems too low
max-statements = 30 # default of 50 seems too high
max-locals = 20     # default of 15 seems too low

[tool.pylint.format]
indent-string = "\t"

[tool.pylint.refactoring]
max-nested-blocks = 2 # default of 5 is too high

# warnings to disable
[tool.pylint.messages_control]
disable = [
	"missing-module-docstring",      # i don't see a need for this
	"too-many-positional-arguments", # i don't see a need for this
]
