[tool.codespell]
skip = "*.geojson,*.nmea,*.tsv,*.lock,*.svg,./views/map/*.txt,dist,node_modules"

[tool.ruff]
line-length = 100
lint.select = [
	"B",
	"C4",
	"C90",
	"E",
	"F",
	"ICN",
	"PERF",
	"PIE",
	"PL",
	"RET",
	"RUF",
	"SIM",
	"W",
	"I",
]
lint.ignore = ["W191"]
lint.mccabe.max-complexity = 14
lint.pylint.allow-magic-value-types = ["float", "int", "str"]
lint.pylint.max-args = 8 # Default is 5

[tool.ruff.format]
indent-style = "tab"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = ["."]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = ["dataclass_wizard.*", "h3.*", "pynmeagps.*"]
follow_untyped_imports = true
