# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://docs.astral.sh/ruff/
name: ci
on:
  push:
    # branches: [main]
  pull_request:
    # branches: [main]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: codespell-project/actions-codespell@v2
    - uses: astral-sh/ruff-action@v3
      with:
        version: "latest"
